name: RealFireworks
version: '${project.version}'
main: me.gamehugo.realfireworks.RealFireworks
api-version: 1.16
authors: [ GameHugo_ ]
description: '${project.description}'
website: https://cheesydevs.nl
commands:
  realfireworks:
    description: "The main command of the realfireworks plugin"
    aliases: [rf]
permissions:
  realfireworks.use:
    description: "The main command of the realfireworks plugin"
